### ISSUE TITLE
Proposal: deprecate maybot 

### ISSUE THREAD

**Issue by hugo** [andrewfairlie/maybot#7]
The time has come for maybot to be retired and a viable replacement found.

- Support for maybot has been drying up at an alarming pace, even as the number of glaring issues increases almost as rapidly.
- Maybot doesn't act according to its documentation, which is also woefully out of date and.
- Maybot ignores SIGTERM interrupts and keeps running long after it should have stopped.

I also note that in the event of a panic, maybot is unable to handle the event gracefully, and instead performs the strange action of trying to take control of other processes from the operating system before shutting them down.

For these reason, and many others, I propose that maybot be immediately retired and replaced.

**Comment by Clidus** [comment]
+1
